# Generated by Django 5.2.8 on 2025-11-05 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=128, unique=True)),
                ("source_account", models.CharField(max_length=128)),
                ("destination_account", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSING", "Processing"),
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("FAILED", "Failed"),
                            ("PROCESSED", "Processed"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("task_enqueued", models.BooleanField(default=False)),
            ],
        ),
    ]
